Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment.Data;
using Assignment.Models;

namespace Assignment.Controllers
{
    public class MenusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Menus
        public async Task<IActionResult> Index()
        {
              return View(await _context.Menus.ToListAsync());
        }

        // GET: Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Menus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Menu menu)
        {
            if (id != menu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Menus == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Menu'  is null.");
            }
            var menu = await _context.Menus.FindAsync(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
          return _context.Menus.Any(e => e.Id == id);
        }
    }
}

Controllers/ShopController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using Stripe.Checkout;

namespace Assignment.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;

        public ShopController(ApplicationDbContext context, IConfiguration config)
        {
            _context = context;
            _config = config;
        }

        // GET Shop/Index
        public IActionResult Index()
        {
            var menus = _context.Menus
                .OrderBy(c => c.Name)
                .ToList();

            return View(menus);
        }

        // GET Shop/Category?Id=123
        public IActionResult Menu(int Id)
        {
            var menu = _context.Menus.Find(Id);

            if (menu == null)
            {
                return NotFound();
            }

            ViewData["MenuName"] = menu.Name;

            var dishes = _context.Dishes
                .Where(d => d.MenuId == Id)
                .Include(d => d.Menu)
                .ToList();

            return View(dishes);
        }

        // GET Shop/Cart
        public IActionResult Cart()
        {
            var customerId = GetCustomerId();

            var cartLines = _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .Include(cl => cl.Dish)
                .OrderByDescending(cl => cl.Id)
                .ToList();

            ViewData["TotalPrice"] = cartLines.Sum(cl => cl.Price).ToString("C");

            return View(cartLines);
        }

        // GET Shop/Checkout
        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            var customerId = GetCustomerId();

            var totalPrice = _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .Sum(cl => cl.Price)
                .ToString("C");

            ViewData["Total"] = totalPrice;

            return View();
        }

        // POST Shop/Checkout
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(
            [Bind("FirstName,LastName,Address,City,Province,PostalCode,Phone")] Order Order
        )
        {
            // Build Order
            Order.OrderDate = DateTime.UtcNow;
            Order.CustomerId = GetCustomerId();
            Order.InProgress = true;

            // Remove old InProgress orders for the customer
            var oldOrders = await _context.Orders
                .Where(o => o.InProgress && o.CustomerId == Order.CustomerId)
                .ToListAsync();

            foreach (var oldOrder in oldOrders)
            {
                _context.Orders.Remove(oldOrder);
            }

            // Get cart lines
            var cartLines = await _context.CartLines
                .Where(cl => cl.CustomerId == Order.CustomerId)
                .ToListAsync();

            Order.Total = cartLines.Sum(cl => cl.Price);

            // Create order
            var CreatedOrder = await _context.Orders.AddAsync(Order);
            await _context.SaveChangesAsync();

            foreach (var cartLine in cartLines)
            {
                // Create OrderLine
                await _context.OrderLines.AddAsync(new OrderLine()
                {
                    Quantity = cartLine.Quantity,
                    Price = cartLine.Price,
                    DishId = cartLine.DishId,
                    OrderId = CreatedOrder.Entity.Id,
                });
            }

            await _context.SaveChangesAsync();

            return Redirect("Payment");
        }

        // GET Shop/Payment
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Payment()
        {
            var customerId = GetCustomerId();

            var order = await GetCurrentOrderAsync(customerId);

            if (order == null)
            {
                return NotFound();
            }

            ViewData["Total"] = order.Total;

            ViewData["PublishableKey"] = _config["Payments:Stripe:PublishableKey"];

            return View();
        }

        // POST Shop/Payment
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Payment(String StripeToken)
        {
            var customerId = GetCustomerId();
            var order = await GetCurrentOrderAsync(customerId);

            // can't access payment process unless there is an ongoing order
            if (order == null)
            {
                return NotFound();
            }

            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long) (order.Total * 100),
                            Currency = "CAD",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Store Purchase",
                            },
                        },
                        Quantity = 1,
                    },
                },
                PaymentMethodTypes = new List<String>
                {
                    "card",
                },
                Mode = "payment",
                SuccessUrl = "https://" + Request.Host + "/Shop/SaveOrder",
                CancelUrl = "https://" + Request.Host + "/Shop/Cart",
            };

            var service = new SessionService();
            var session = service.Create(options);

            Response.Headers.Add("Status", "303");
            Response.Headers.Add("Location", session.Url);

            return Json(new { id = session.Id });
        }

        // GET /Shop/SaveOrder
        [Authorize]
        public async Task<IActionResult> SaveOrder()
        {
            var customerId = GetCustomerId();
            var order = await GetCurrentOrderAsync(customerId);

            if (order == null)
            {
                return NotFound();
            }

            order.InProgress = false;

            var cartLines = await _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .ToListAsync();

            foreach (var cartLine in cartLines)
            {
                _context.CartLines.Remove(cartLine);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Orders", new { @id = order.Id });
        }

        // POST Shop/AddToCart
        [HttpPost]
        public IActionResult AddToCart([FromForm] int DishId, [FromForm] int Quantity)
        {
            if (Quantity <= 0)
            {
                return BadRequest();
            }

            var dish = _context.Dishes.Find(DishId);
            if (dish == null)
            {
                return BadRequest(); // HTTP Status code 400
            }

            var price = dish.Price * Quantity;

            var customerId = GetCustomerId();

            var cartLine = _context.CartLines
                .Where(cl => cl.DishId == DishId && cl.CustomerId == customerId)
                .FirstOrDefault();

            if (cartLine != null)
            {
                cartLine.Quantity += Quantity;
                cartLine.Price += price;

                _context.CartLines.Update(cartLine);
                _context.SaveChanges();
            }
            else
            {
                cartLine = new CartLine()
                {
                    DishId = DishId,
                    Quantity = Quantity,
                    Price = price,
                    CustomerId = customerId,
                };

                _context.CartLines.Add(cartLine);
                _context.SaveChanges();
            }

            return Redirect("Cart");
        }

        // POST Shop/UpdateCart
        [HttpPost]
        public IActionResult UpdateCart([FromForm] int CartLineId, [FromForm] int Quantity)
        {
            if (Quantity <= 0)
            {
                return BadRequest();
            }

            var cartLine = _context.CartLines.Find(CartLineId);

            if (cartLine == null)
            {
                return BadRequest();
            }

            var dish = _context.Dishes.Find(cartLine.DishId);
            var discount = cartLine.Price - (dish.Price * cartLine.Quantity);

            cartLine.Quantity = Quantity;
            cartLine.Price = Math.Max((dish.Price * Quantity) - discount, 0);

            _context.CartLines.Update(cartLine);
            _context.SaveChanges();

            return Redirect("Cart");
        }

        // POST Shop/RemoveFromCart
        [HttpPost]
        public IActionResult RemoveFromCart([FromForm] int CartLineId)
        {
            var cartLine = _context.CartLines.Find(CartLineId);

            if (cartLine == null)
            {
                return BadRequest();
            }

            _context.CartLines.Remove(cartLine);
            _context.SaveChanges();

            return Redirect("Cart");
        }



        private async Task<Order?> GetCurrentOrderAsync(String customerId)
        {
            var orders = await _context.Orders
                .Where(o => o.InProgress && o.CustomerId == customerId)
                .ToListAsync();

            if (orders.Count() == 0)
            {
                return null;
            }

            return orders[0];
        }
        private String GetCustomerId()
        {
            var isLoggedIn = User?.Identity?.IsAuthenticated ?? false;

            if (isLoggedIn)
            {

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow p-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menus" asp-action="Index">Menus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dishes" asp-action="Index">Dishes</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>  
                    </ul>

                    <a class="navbar-brand flex-grow-1" asp-area="" asp-controller="Home" asp-action="Index">PetiteKitchen.</a>

                    <ul class="navbar-nav ">
                        <li class="nav-item position-relative d-flex">                            
                            <a class="nav-link text-dark" asp-controller="Shop" asp-action="Cart">
                                <image  style="width: 20px; height: 20px;" src="https://cdn-icons-png.flaticon.com/512/1170/1170678.png" alt="cart" />
                            </a>
                            <span class="position-absolute d-flex justify-content-center align-items-center" style="font-size: 5px; background-color: rgba(255, 0, 0, 0.9); color: white;border-radius: 50%; height: 20px; width: 20px; top: 0; right: 0;">2</span> 
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="max-width: 100%; margin: 0; padding: 0;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position: relative;">
        <div class="container d-flex flex-column align-items-center ">
            <p>&copy; 2023 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Index">Petite Kitchen</a></p>
            <p>Do Minh Quang (Wayne) Nguyen - 200501387</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>