Models/Menu.cs
namespace Assignment.Models
{
    public class Menu
    {
        public int Id { get; set; }

        public String? Name { get; set; }   

        public String? Description { get; set; }

        public List<Dish>? Dishes { get; set; }

    }
}

Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace Assignment.Controllers
{
    public class DishesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DishesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dishes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dishes.Include(d => d.Menu);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Menu)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // GET: Dishes/Create
        public IActionResult Create()
        {
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id");
            return View();
        }

        // POST: Dishes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317Dishes98.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Image,MenuId")] Dish dish, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    dish.Image = UploadPhoto(Image);
                }
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", dish.MenuId);
            return View(dish);
        }

        // GET: Dishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes.FindAsync(id);
            if (dish == null)
            {
                return NotFound();
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", dish.MenuId);
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Image,MenuId")] Dish dish)
        {
            if (id != dish.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DishExists(dish.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", dish.MenuId);
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Dishes == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .Include(d => d.Menu)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Dishes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Dish'  is null.");
            }
            var dish = await _context.Dishes.FindAsync(id);
            if (dish != null)
            {
                _context.Dishes.Remove(dish);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
          return _context.Dishes.Any(e => e.Id == id);
        }

        private static string UploadPhoto(IFormFile Photo)
        {
            // use GUID (Globally Unique ID) to create a unique image name
            // logo.jpg => fbdjqb32153-logo.jpg
            var fileName = Guid.NewGuid().ToString() + "-" + Photo.FileName;

            // Set a destination filepath dynamically (so it works locally and on the server)
            var uploadPath = Directory.GetCurrentDirectory() + "\\wwwroot\\img\\dishes\\" + fileName;

            // Write the uploaded file into our destination (wwwroot/img/products/...)
            using (var stream = new FileStream(uploadPath, FileMode.Create))
            {
                Photo.CopyTo(stream);
            }

            return fileName;
        }

        private static void DeletePhoto(string Photo)
        {
            var path = Directory.GetCurrentDirectory() + "\\wwwroot\\img\\dishes\\" + Photo;

            try
            {
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }
            catch (IOException e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
}

Controllers/ShopController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using Stripe.Checkout;

namespace Assignment.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;

        public ShopController(ApplicationDbContext context, IConfiguration config)
        {
            _context = context;
            _config = config;
        }

        // GET Shop/Index
        public IActionResult Index()
        {
            var menus = _context.Menus
                .OrderBy(c => c.Name)
                .ToList();

            return View(menus);
        }

        // GET Shop/Category?Id=123
        public IActionResult Menu(int Id)
        {
            var menu = _context.Menus.Find(Id);

            if (menu == null)
            {
                return NotFound();
            }

            ViewData["MenuName"] = menu.Name;

            var dishes = _context.Dishes
                .Where(d => d.MenuId == Id)
                .Include(d => d.Menu)
                .ToList();

            return View(dishes);
        }

        // GET Shop/Cart
        public IActionResult Cart()
        {
            var customerId = GetCustomerId();

            var cartLines = _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .Include(cl => cl.Dish)
                .OrderByDescending(cl => cl.Id)
                .ToList();

            ViewData["TotalPrice"] = cartLines.Sum(cl => cl.Price).ToString("C");

            return View(cartLines);
        }

        // GET Shop/Checkout
        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            var customerId = GetCustomerId();

            var totalPrice = _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .Sum(cl => cl.Price)
                .ToString("C");

            ViewData["Total"] = totalPrice;

            return View();
        }

        // POST Shop/Checkout
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(
            [Bind("FirstName,LastName,Address,City,Province,PostalCode,Phone")] Order Order
        )
        {
            // Build Order
            Order.OrderDate = DateTime.UtcNow;
            Order.CustomerId = GetCustomerId();
            Order.InProgress = true;

            // Remove old InProgress orders for the customer
            var oldOrders = await _context.Orders
                .Where(o => o.InProgress && o.CustomerId == Order.CustomerId)
                .ToListAsync();

            foreach (var oldOrder in oldOrders)
            {
                _context.Orders.Remove(oldOrder);
            }

            // Get cart lines
            var cartLines = await _context.CartLines
                .Where(cl => cl.CustomerId == Order.CustomerId)
                .ToListAsync();

            Order.Total = cartLines.Sum(cl => cl.Price);

            // Create order
            var CreatedOrder = await _context.Orders.AddAsync(Order);
            await _context.SaveChangesAsync();

            foreach (var cartLine in cartLines)
            {
                // Create OrderLine
                await _context.OrderLines.AddAsync(new OrderLine()
                {
                    Quantity = cartLine.Quantity,
                    Price = cartLine.Price,
                    DishId = cartLine.DishId,
                    OrderId = CreatedOrder.Entity.Id,
                });
            }

            await _context.SaveChangesAsync();

            return Redirect("Payment");
        }

        // GET Shop/Payment
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Payment()
        {
            var customerId = GetCustomerId();

            var order = await GetCurrentOrderAsync(customerId);

            if (order == null)
            {
                return NotFound();
            }

            ViewData["Total"] = order.Total;

            ViewData["PublishableKey"] = _config["Payments:Stripe:PublishableKey"];

            return View();
        }

        // POST Shop/Payment
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Payment(String StripeToken)
        {
            var customerId = GetCustomerId();
            var order = await GetCurrentOrderAsync(customerId);

            // can't access payment process unless there is an ongoing order
            if (order == null)
            {
                return NotFound();
            }

            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long) (order.Total * 100),
                            Currency = "CAD",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Store Purchase",
                            },
                        },
                        Quantity = 1,
                    },
                },
                PaymentMethodTypes = new List<String>
                {
                    "card",
                },
                Mode = "payment",
                SuccessUrl = "https://" + Request.Host + "/Shop/SaveOrder",
                CancelUrl = "https://" + Request.Host + "/Shop/Cart",
            };

            var service = new SessionService();
            var session = service.Create(options);

            Response.Headers.Add("Status", "303");
            Response.Headers.Add("Location", session.Url);

            return Json(new { id = session.Id });
        }

        // GET /Shop/SaveOrder
        [Authorize]
        public async Task<IActionResult> SaveOrder()
        {
            var customerId = GetCustomerId();
            var order = await GetCurrentOrderAsync(customerId);

            if (order == null)
            {
                return NotFound();
            }

            order.InProgress = false;

            var cartLines = await _context.CartLines
                .Where(cl => cl.CustomerId == customerId)
                .ToListAsync();

            foreach (var cartLine in cartLines)
            {
                _context.CartLines.Remove(cartLine);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Orders", new { @id = order.Id });
        }

        // POST Shop/AddToCart
        [HttpPost]
        public IActionResult AddToCart([FromForm] int DishId, [FromForm] int Quantity)
        {
            if (Quantity <= 0)
            {
                return BadRequest();
            }

            var dish = _context.Dishes.Find(DishId);
            if (dish == null)
            {
                return BadRequest(); // HTTP Status code 400
            }

            var price = dish.Price * Quantity;

            var customerId = GetCustomerId();

            var cartLine = _context.CartLines
                .Where(cl => cl.DishId == DishId && cl.CustomerId == customerId)
                .FirstOrDefault();

            if (cartLine != null)
            {
                cartLine.Quantity += Quantity;
                cartLine.Price += price;

                _context.CartLines.Update(cartLine);
                _context.SaveChanges();
            }
            else
            {
                cartLine = new CartLine()
                {
                    DishId = DishId,
                    Quantity = Quantity,
                    Price = price,
                    CustomerId = customerId,
                };

                _context.CartLines.Add(cartLine);
                _context.SaveChanges();
            }

            return Redirect("Cart");
        }

        // POST Shop/UpdateCart
        [HttpPost]
        public IActionResult UpdateCart([FromForm] int CartLineId, [FromForm] int Quantity)
        {
            if (Quantity <= 0)
            {
                return BadRequest();
            }

            var cartLine = _context.CartLines.Find(CartLineId);

            if (cartLine == null)
            {
                return BadRequest();
            }

            var dish = _context.Dishes.Find(cartLine.DishId);
            var discount = cartLine.Price - (dish.Price * cartLine.Quantity);

            cartLine.Quantity = Quantity;
            cartLine.Price = Math.Max((dish.Price * Quantity) - discount, 0);

            _context.CartLines.Update(cartLine);
            _context.SaveChanges();

            return Redirect("Cart");
        }

        // POST Shop/RemoveFromCart
        [HttpPost]
        public IActionResult RemoveFromCart([FromForm] int CartLineId)
        {
            var cartLine = _context.CartLines.Find(CartLineId);

            if (cartLine == null)
            {
                return BadRequest();
            }

            _context.CartLines.Remove(cartLine);
            _context.SaveChanges();

            return Redirect("Cart");
        }



        private async Task<Order?> GetCurrentOrderAsync(String customerId)
        {
            var orders = await _context.Orders
                .Where(o => o.InProgress && o.CustomerId == customerId)
                .ToListAsync();

            if (orders.Count() == 0)
            {
                return null;
            }

            return orders[0];
        }
        private String GetCustomerId()
        {
            var isLoggedIn = User?.Identity?.IsAuthenticated ?? false;

            if (isLoggedIn)
            {

Views/Shop/Cart.cshtml
@model IEnumerable<Assignment.Models.CartLine>
@{
    ViewData["Title"] = "Cart";
}

<h1>Cart</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Dish.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dish)
            </th>
            <th>
                Price per
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                Total Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @if (item.Dish.Image != null)
                {
                    <img class="thumbnail" src="~/img/dishs/@item.Dish.Image" alt="Dish Photo" />
                }
            </td>
            <td>
                <a asp-controller="Dishes" asp-action="Details" asp-route-id="@item.Dish.Id">@item.Dish.Name</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dish.Price)
            </td>
            <td>
                <form method="POST" action="/Shop/UpdateCart">
                    <input type="hidden" id="CartLineId" name="CartLineId" value="@item.Id" />
                    <input name="Quantity" id="Quantity" required type="number" min="1" max="999" value="@item.Quantity" />
                    <button class="btn btn-primary btn-sm">Update</button>
                </form>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <form method="POST" action="/Shop/RemoveFromCart">
                    <input type="hidden" id="CartLineId" name="CartLineId" value="@item.Id" />
                    <button class="btn btn-danger btn-sm">Remove</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

<h3>Total: @ViewData["TotalPrice"]</h3>

<a class="btn btn-success" asp-controller="Shop" asp-action="Checkout">Checkout</a>

Views/Shop/Checkout.cshtml
@model Assignment.Models.Order
@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Checkout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <h4>Total: @ViewData["Total"]</h4>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue to Payment" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Cart">Back to Cart</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shop/Index.cshtml
@model IEnumerable<Assignment.Models.Menu>

@{
    ViewData["Title"] = "Choose A Menu";
}

<h1>Choose A Menu</h1>

<section class="row card-group">
    @foreach(var menu in Model)
    {
        <div class="col-lg-4 mb-3">
            <div class="card mb-4">
                <div class="card-body text-center h-100">
                    <a asp-action="Menu" asp-route-id="@menu.Id">@menu.Name</a>
                </div>
            </div>
        </div>
    }
</section>

Views/Shop/Menu.cshtml
@model IEnumerable<Assignment.Models.Dish>
@{
    ViewData["Title"] = "Shop by " + ViewData["MenuName"];
}

<h1>Shop by @ViewData["MenuName"]</h1>

<section class="row card-group">
    @foreach(var dish in Model)
    {
        <div class="col-lg-4 mb-3">
            <div class="card mb-4">
                <div class="card-body text-center h-100">
                    @if(dish.Image != null)
                    {
                        <img
                       src="~/img/dishes/@dish.Image" 
                       alt="photo of @dish.Name"
                       class="img-thumbnail"
                        />
                    }
                    <a asp-controller="Dishes" asp-action="Details" asp-route-id="@dish.Id">
                        @dish.Name
                    </a>
                    <h6>@dish.Price.ToString("C")</h6>                    
                    
                    <form method="POST" action="/Shop/AddToCart">
                        <input type="hidden" id="DishId" name="DishId" value="@dish.Id" />
                        <input type="hidden" id="Quantity" name="Quantity" value="1" />

                        <button class="btn btn-primary">Add to Cart</button>
                    </form>
                </div>
            </div>
        </div>
    }
</section>

Views/Shop/Payment.cshtml
@{
    ViewData["Title"] = "Payment";
}

<h1>Process Payment</h1>

<script src="https://js.stripe.com/v3"></script>

<button id="checkout">Pay</button>

<script type="text/javascript">
    var stripe = Stripe("@ViewData["PublishableKey"]");
    var checkoutBtn = document.getElementById("checkout");
    checkoutBtn.addEventListener("click", () => {
        fetch("/Shop/Payment",
        {
            method: "POST",
        })
        .then(res => res.json())
        .then(session => {
            return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(res => {
            console.log(res);
            if (res.error)
            {
                alert(res.error.message);
            }
        })
        .catch(e => console.error(e));
    });
</script>